# qrun benchmarks/LightGBM/workflow_config_lightgbm_Alpha158_multi_freq_test.yaml
qlib_init:
    provider_uri:
        day: "D:/ProgramCoding/Data/stock_data/qlib_data/hs300_1d_bin"
        5min: "D:/ProgramCoding/Data/stock_data/qlib_data/hs300_5min_bin"
    region: cn
    dataset_cache: null
    maxtasksperchild: 1
market: &market csi300
benchmark: &benchmark SH000300
data_handler_config: &data_handler_config
    start_time: 2024-05-06
    # 5min closing time is 14:55:00
    end_time: "2025-04-16 14:55:00"
    fit_start_time: 2024-05-06
    fit_end_time: 2024-11-30
    instruments: *market
    freq:
        label: day
        feature: 5min
    # with label as reference
    inst_processors:
        feature:
            - class: Resample5minProcessor
              module_path: features_sample.py
              kwargs:
                  hour: 14
                  minute: 55

port_analysis_config: &port_analysis_config
    strategy:
        class: TopkDropoutStrategy
        module_path: qlib.contrib.strategy.strategy
        kwargs:
            topk: 30
            n_drop: 2
            signal: <PRED>
    backtest:
        verbose: False
        limit_threshold: 0.095
        account: 100000000
        benchmark: *benchmark
        deal_price: close
        open_cost: 0.0005
        close_cost: 0.0015
        min_cost: 5
task:
    model:
        class: LGBModel
        module_path: qlib.contrib.model.gbdt
        kwargs:
            loss: mse
            colsample_bytree: 0.8879
            learning_rate: 0.2
            subsample: 0.8789
            lambda_l1: 205.6999
            lambda_l2: 580.9768
            max_depth: 8
            num_leaves: 210
            num_threads: 20
    dataset:
        class: DatasetH
        module_path: qlib.data.dataset
        kwargs:
            handler:
                class: Alpha158
                module_path: qlib.contrib.data.handler
                kwargs: *data_handler_config
            segments:
                train: [2024-05-06, 2024-11-30]
                valid: [2024-12-01, 2025-02-28]
                test: [2025-03-01, 2025-04-01]
    record: 
        - class: SignalRecord
          module_path: qlib.workflow.record_temp
          kwargs: {}
        - class: SigAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            ana_long_short: False
            ann_scaler: 252
        - class: PortAnaRecord
          module_path: qlib.workflow.record_temp
          kwargs: 
            config: *port_analysis_config
